use_frameworks!

platform :ios, '9.0'

target 'XMVerificationCodeInputView_Example' do
  pod 'XMVerificationCodeInputView', :path => '../'

  target 'XMVerificationCodeInputView_Tests' do
    inherit! :search_paths

    
  end
end
